import { TurboAttribution } from '../lib/api/questions'

interface TurboAnswerCardProps {
  answer: string
  confidence: number
  threshold: number
  attributions: TurboAttribution[]
  onAccept: () => void
  onReject: () => void
  isProcessing?: boolean
}

export default function TurboAnswerCard({
  answer,
  confidence,
  threshold,
  attributions,
  onAccept,
  onReject,
  isProcessing = false,
}: TurboAnswerCardProps) {
  const confidencePercent = Math.round(confidence * 100)
  const thresholdPercent = Math.round(threshold * 100)

  // Confidence level indicator
  const getConfidenceLevel = () => {
    if (confidence >= 0.9) return { label: 'High', class: 'text-status-success' }
    if (confidence >= 0.75) return { label: 'Good', class: 'text-status-success' }
    if (confidence >= 0.5) return { label: 'Moderate', class: 'text-status-warning' }
    return { label: 'Low', class: 'text-status-error' }
  }

  const confidenceLevel = getConfidenceLevel()

  return (
    <div className="card-tufte card-elevated">
      {/* Header with Turbo Loris branding */}
      <div className="flex items-start gap-4 mb-6">
        <img
          src="/loris-images/TransWarp_Loris.png"
          alt="Turbo Loris"
          className="h-20 w-auto"
        />
        <div>
          <h3 className="font-mono text-xs text-ink-tertiary tracking-wide uppercase flex items-center gap-2">
            <span className="text-status-warning">*</span>
            Turbo Loris Answer
          </h3>
          <p className="font-serif text-sm text-ink-secondary mt-1">
            Instant answer based on validated knowledge
          </p>
        </div>
      </div>

      {/* Confidence meter */}
      <div className="mb-6">
        <div className="flex items-center justify-between mb-1">
          <span className="font-mono text-xs text-ink-secondary">
            Confidence: <span className={confidenceLevel.class}>{confidencePercent}%</span>
            <span className="text-ink-muted"> ({confidenceLevel.label})</span>
          </span>
          <span className="font-mono text-[10px] text-ink-muted">
            Threshold: {thresholdPercent}%
          </span>
        </div>
        <div className="h-2 bg-cream-200 rounded-sm overflow-hidden">
          <div
            className={`h-full transition-all ${
              confidence >= threshold ? 'bg-status-success' : 'bg-status-warning'
            }`}
            style={{ width: `${confidencePercent}%` }}
          />
        </div>
      </div>

      {/* Answer content */}
      <div className="font-serif text-ink-primary leading-relaxed mb-6 whitespace-pre-wrap">
        {answer}
      </div>

      {/* Attributions */}
      {attributions.length > 0 && (
        <div className="border-t border-rule-light pt-4 mb-6">
          <h4 className="font-mono text-xs text-ink-tertiary tracking-wide uppercase mb-3">
            Sources
          </h4>
          <ul className="space-y-2">
            {attributions.slice(0, 5).map((attr) => (
              <li key={attr.id} className="flex items-start gap-2 text-sm">
                <span className="font-mono text-[10px] text-ink-muted mt-0.5">
                  {Math.round(attr.semantic_similarity * 100)}%
                </span>
                <div>
                  <span className="font-serif text-ink-secondary">
                    {attr.display_name.length > 100
                      ? `${attr.display_name.slice(0, 100)}...`
                      : attr.display_name}
                  </span>
                  {attr.contributor_name && (
                    <span className="font-mono text-[10px] text-ink-muted ml-2">
                      ({attr.contribution_type} by {attr.contributor_name})
                    </span>
                  )}
                </div>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Actions */}
      <div className="flex items-center gap-4">
        <button
          onClick={onAccept}
          disabled={isProcessing}
          className="btn-primary disabled:opacity-50"
        >
          {isProcessing ? 'Processing...' : 'This helped'}
        </button>
        <button
          onClick={onReject}
          disabled={isProcessing}
          className="btn-secondary disabled:opacity-50"
        >
          Request expert review
        </button>
      </div>

      {/* Disclaimer */}
      <p className="font-mono text-[10px] text-ink-muted mt-4">
        This answer was generated by AI based on your organization's knowledge base.
        For critical matters, please request expert review.
      </p>
    </div>
  )
}
